env:
  vehicles_count: 10
  initial_vehicle_count: 10
  absolute: True
  normalize: False
  order: sorted
  spawn_probability: 0.3
pure_mpc:
  horizon: 16
  render: False
  ttc_threshold: 2
mpc_rl:

rl: