env:
  vehicles_count: 20
  initial_vehicle_count: 10
  absolute: True
  normalize: False
  order: sorted
  spawn_probability: 0.3

pure_mpc:
  # mpc parameters 
  horizon: 16
  # render options
  render: true
  render_window_size: 6
  render_axis_range: 50
  # collision detection parameters
  ttc_threshold: 1
  detection_distance: 100
  speed_override: 0
  # weight parameters
  weight_state: 10
  weight_control: 1
  weight_final_state: 1
  weight_input_diff: 1
  weight_distance: 10
  weight_collision: 1

mpc_rl:

  v0: # reference speed version
    action_space_dim: 85
    algo: ppo
    lr: 0.000001
    n_steps: 800
    batch_size: 64
    n_epochs: 10
    total_timesteps: 500      
    show_progress_bar: True

  v1: # dynamic weights version
    action_space_dim: 10
    algo: ppo
    lr: 0.000001
    n_steps: 800
    batch_size: 64
    n_epochs: 10
    total_timesteps: 3e3    
    show_progress_bar: True
rl:
