env:
  vehicles_count: 20
  initial_vehicle_count: 10
  absolute: True
  normalize: False
  order: sorted
  spawn_probability: 0.3

pure_mpc:
  horizon: 16
  render: true
  ttc_threshold: 2
  speed_override: 0
  weight_state: 10
  weight_control: 1
  weight_final_state: 1
  weight_input_diff: 1
  weight_distance: 1
  weight_collision: 1

mpc_rl:

  v0: # reference speed version
    action_space_dim: 10
    algo: a2c
    lr: 0.0001
    total_timesteps: 2e3      
    show_progress_bar: True

  v1: # dynamic weights version
    action_space_dim: 10
    algo: ppo

rl: